import CycleDoubleCover.QuotientRepresentation

/-!
# Column-generated complements for actual contraction interfaces

A subspace of a represented column span has a complement generated by original
columns. Quotient-basis selection proves this over an arbitrary field, without
requiring a one-dimensional interface.
-/

namespace CycleDoubleCover.MatroidPaper

open Set Module
open scoped Matroid

/-- A complement to a prescribed subspace can be selected from the original
columns, with those selected columns remaining independent. -/
theorem exists_column_span_complement {α F : Type*} [Field F] {n : ℕ}
    (ρ : α → Fin n → F) (B : Set α) (S : Submodule F (Fin n → F))
    (hS : S ≤ Submodule.span F (ρ '' B)) :
    ∃ C ⊆ B, LinearIndepOn F ρ C ∧
      Disjoint (Submodule.span F (ρ '' C)) S ∧
      Submodule.span F (ρ '' B) = Submodule.span F (ρ '' C) ⊔ S := by
  classical
  let q := S.mkQ
  let σ : α → (Fin n → F) ⧸ S := q ∘ ρ
  obtain ⟨C, hCB, _, hspan, hli⟩ :=
    exists_linearIndepOn_extension (v := σ) (linearIndepOn_empty F σ) (empty_subset B)
  have hdisj : Disjoint (Submodule.span F (ρ '' C)) S := by
    have h := Submodule.range_ker_disjoint (f := q) (v := fun e : C => ρ e.val) hli
    simpa only [q, ← Set.image_eq_range, Submodule.ker_mkQ] using h
  have hmap : (Submodule.span F (ρ '' B)).map q =
      (Submodule.span F (ρ '' C)).map q := by
    rw [Submodule.map_span, Submodule.map_span]
    simp only [Set.image_image]
    change Submodule.span F (σ '' B) = Submodule.span F (σ '' C)
    exact le_antisymm (Submodule.span_le.mpr hspan)
      (Submodule.span_mono (Set.image_mono hCB))
  have hsup := congrArg (Submodule.comap q) hmap
  dsimp only [q] at hsup
  rw [Submodule.comap_map_eq, Submodule.comap_map_eq, Submodule.ker_mkQ,
    sup_eq_left.mpr hS] at hsup
  exact ⟨C, hCB, LinearIndependent.of_comp q hli, hdisj, hsup⟩

/-- Contraction of a selected complementary column set preserves every
independent vector in the prescribed interface subspace. -/
theorem contractionProjection_injective_on_disjoint_span
    {α F : Type*} [Field F] {n : ℕ} (ρ : α → Fin n → F) (C : Set α)
    (S : Submodule F (Fin n → F))
    (hdisj : Disjoint S (Submodule.span F (ρ '' C))) :
    Set.InjOn (contractionProjection ρ C) S := by
  intro x hx y hy hxy
  have hz : contractionProjection ρ C (x - y) = 0 := by
    rw [map_sub, hxy, sub_self]
  have hc := (contractionProjection_eq_zero_iff ρ C _).mp hz
  have hzero : x - y = 0 :=
    (Submodule.disjoint_def.mp hdisj) _ (S.sub_mem hx hy) hc
  exact sub_eq_zero.mp hzero

/-- Contract original columns of the second side to its common interface,
preserving all independence on the first side. The retained second side has
exactly the rank of the actual common subspace. -/
theorem Represents.exists_contraction_to_common_interface
    {α F : Type*} [Finite α] [Field F] {n : ℕ} {M : Matroid α}
    {ρ : α → Fin n → F} (hρ : Represents M F ρ) {A B : Set α}
    (hA : A ⊆ M.E) (hB : B ⊆ M.E) (hAB : Disjoint A B) :
    ∃ C ⊆ B, M.Indep C ∧
      Set.InjOn (contractionProjection ρ C) (Submodule.span F (ρ '' A)) ∧
      (∀ I ⊆ A, (M ／ C).Indep I ↔ M.Indep I) ∧
      MatroidUnion.rank (M ／ C) (B \ C) =
        finrank F ↥(Submodule.span F (ρ '' A) ⊓ Submodule.span F (ρ '' B)) := by
  classical
  let S := Submodule.span F (ρ '' A) ⊓ Submodule.span F (ρ '' B)
  obtain ⟨C, hCB, hliC, hdisj, hspan⟩ :=
    exists_column_span_complement ρ B S inf_le_right
  have hCE : C ⊆ M.E := hCB.trans hB
  have hind : M.Indep C := (hρ C).mpr ⟨hCE, hliC⟩
  have hdisjA : Disjoint (Submodule.span F (ρ '' A))
      (Submodule.span F (ρ '' C)) := by
    apply Submodule.disjoint_def.mpr
    intro x hxA hxC
    have hxB : x ∈ Submodule.span F (ρ '' B) :=
      Submodule.span_mono (Set.image_mono hCB) hxC
    exact (Submodule.disjoint_def.mp hdisj) x hxC ⟨hxA, hxB⟩
  have hinj := contractionProjection_injective_on_disjoint_span ρ C
    (Submodule.span F (ρ '' A)) hdisjA
  refine ⟨C, hCB, hind, hinj, ?_, ?_⟩
  · intro I hIA
    have hIE := hIA.trans hA
    have hIC : Disjoint I C := hAB.mono hIA hCB
    have hIE' : I ⊆ (M ／ C).E := by
      rw [Matroid.contract_ground]
      exact subset_sdiff.mpr ⟨hIE, hIC⟩
    rw [hρ.contract_quotient hCE, hρ, and_iff_right hIE', and_iff_right hIE]
    change LinearIndepOn F ((contractionProjection ρ C) ∘ ρ) I ↔ LinearIndepOn F ρ I
    exact (contractionProjection ρ C).linearIndepOn_iff_of_injOn
      (hinj.mono (Submodule.span_mono (Set.image_mono hIA)))
  · have hrank := MatroidUnion.rank_contract_add M hCE (sdiff_subset.trans hB)
      (Set.disjoint_sdiff_right.mono_left subset_rfl)
    rw [Set.union_sdiff_cancel hCB] at hrank
    have hdim := Submodule.finrank_sup_add_finrank_inf_eq
      (Submodule.span F (ρ '' C)) S
    rw [hdisj.eq_bot, finrank_bot, add_zero, ← hspan,
      ← hρ.rank_eq_finrank_span hCE, ← hρ.rank_eq_finrank_span hB] at hdim
    change MatroidUnion.rank (M ／ C) (B \ C) = finrank F S
    omega

/-- Contraction preserves the no-coloop premise without any cover hypothesis. -/
theorem HasNoColoops.contract {α : Type*} {M : Matroid α} (hno : HasNoColoops M)
    (C : Set α) : HasNoColoops (M ／ C) := by
  intro e he
  exact hno e (Matroid.contract_isColoop_iff.mp he).1

end CycleDoubleCover.MatroidPaper
