import CycleDoubleCover.FanoGeneralLiftCoordinates

/-! Ground-selected quotient charts for arbitrary independent Fano lifts. -/

namespace CycleDoubleCover.MatroidPaper

open Set Module
open scoped Matroid

/-- A prescribed independent column set disjoint from an interface extends
to a complement generated by actual ground columns. -/
theorem exists_column_span_complement_extension {α F : Type*} [Field F] {n : ℕ}
    (ρ : α → Fin n → F) (E C : Set α) (S : Submodule F (Fin n → F))
    (hCE : C ⊆ E) (hC : LinearIndepOn F ρ C)
    (hdis : Disjoint (Submodule.span F (ρ '' C)) S)
    (hS : S ≤ Submodule.span F (ρ '' E)) :
    ∃ B ⊆ E, C ⊆ B ∧ LinearIndepOn F ρ B ∧
      Disjoint (Submodule.span F (ρ '' B)) S ∧
      S ⊔ Submodule.span F (ρ '' B) = Submodule.span F (ρ '' E) := by
  classical
  let q := S.mkQ
  let σ : α → (Fin n → F) ⧸ S := q ∘ ρ
  have hinj : Set.InjOn q (Submodule.span F (ρ '' C)) := by
    apply LinearMap.injOn_of_disjoint_ker le_rfl
    simpa only [q, Submodule.ker_mkQ] using hdis
  have hσC : LinearIndepOn F σ C := (q.linearIndepOn_iff_of_injOn hinj).mpr hC
  obtain ⟨B, hBE, hCB, hspan, hli⟩ := exists_linearIndepOn_extension hσC hCE
  have hBdis : Disjoint (Submodule.span F (ρ '' B)) S := by
    have h := Submodule.range_ker_disjoint (f := q) (v := fun b : B => ρ b.val) hli
    simpa only [q, ← Set.image_eq_range, Submodule.ker_mkQ] using h
  have hmap : (Submodule.span F (ρ '' E)).map q =
      (Submodule.span F (ρ '' B)).map q := by
    rw [Submodule.map_span, Submodule.map_span]
    simp only [Set.image_image]
    change Submodule.span F (σ '' E) = Submodule.span F (σ '' B)
    exact le_antisymm (Submodule.span_le.mpr hspan)
      (Submodule.span_mono (Set.image_mono hBE))
  have hsup := congrArg (Submodule.comap q) hmap
  dsimp only [q] at hsup
  rw [Submodule.comap_map_eq, Submodule.comap_map_eq, Submodule.ker_mkQ,
    sup_eq_left.mpr hS] at hsup
  exact ⟨B, hBE, hCB, LinearIndependent.of_comp q hli, hBdis,
    (sup_comm _ _).trans hsup.symm⟩

variable {α : Type*} [Finite α] {M : Matroid α} {n : ℕ}
  {ρ : α → Fin n → ZMod 2}

omit [Finite α] in
/-- Seven actual lifted columns together with their actual support basis
span the common section, even when no point lies in that section itself. -/
theorem fano_lift_plane_le_ground_span
    (C : Set α) (hCE : C ⊆ M.E)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2))
    (g : FanoPoint ↪ α) (D : FanoPoint → Finset C)
    (hlift : ∀ p : FanoPoint, g p ∈ M.E ∧
      ρ (g p) = ι p.val + ∑ b ∈ D p, ρ b.val) :
    LinearMap.range ι ≤ Submodule.span (ZMod 2) (ρ '' M.E) := by
  rintro _ ⟨x, rfl⟩
  by_cases hx : x = 0
  · rw [hx, map_zero]; exact Submodule.zero_mem _
  · let p : FanoPoint := ⟨x, hx⟩
    have hsum : (∑ b ∈ D p, ρ b.val) ∈ Submodule.span (ZMod 2) (ρ '' M.E) := by
      apply Submodule.sum_mem
      intro b _
      exact Submodule.subset_span ⟨b.val, hCE b.property, rfl⟩
    have hg : ρ (g p) ∈ Submodule.span (ZMod 2) (ρ '' M.E) :=
      Submodule.subset_span ⟨g p, (hlift p).1, rfl⟩
    have heq : ι x = ρ (g p) - ∑ b ∈ D p, ρ b.val := by
      rw [(hlift p).2]; change ι x = ι x + _ - _; abel
    rw [heq]
    exact Submodule.sub_mem _ hg hsum

/-- A full quotient chart may preserve prescribed actual lifted-point
supports, rather than choosing unrelated coordinates for those points. -/
theorem exists_fano_support_chart_preserving_lift
    (B : Set α) (hBE : B ⊆ M.E) (hB : LinearIndepOn (ZMod 2) ρ B)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hdis : Disjoint (Submodule.span (ZMod 2) (ρ '' B)) (LinearMap.range ι))
    (hspan : LinearMap.range ι ⊔ Submodule.span (ZMod 2) (ρ '' B) =
      Submodule.span (ZMod 2) (ρ '' M.E))
    (g : FanoPoint ↪ α) (T : FanoPoint → Finset α)
    (hT : ∀ p, (T p : Set α) ⊆ B)
    (hlift : ∀ p, g p ∈ M.E ∧ ρ (g p) = ι p.val + ∑ b ∈ T p, ρ b) :
    ∃ (t : α → BinaryVector) (D : α → Finset α),
      FanoSupportChart M ρ ι t B D ∧
      ∀ p, t (g p) = p.val ∧ D (g p) = T p := by
  classical
  have hgB (p : FanoPoint) : g p ∉ B := by
    intro hpB
    have hsum : (∑ b ∈ T p, ρ b) ∈ Submodule.span (ZMod 2) (ρ '' B) := by
      apply Submodule.sum_mem
      intro b hb
      exact Submodule.subset_span ⟨b, hT p hb, rfl⟩
    have hcol : ρ (g p) ∈ Submodule.span (ZMod 2) (ρ '' B) :=
      Submodule.subset_span ⟨g p, hpB, rfl⟩
    have hi : ι p.val ∈ Submodule.span (ZMod 2) (ρ '' B) := by
      have heq : ι p.val = ρ (g p) - ∑ b ∈ T p, ρ b := by rw [(hlift p).2]; abel
      rw [heq]; exact Submodule.sub_mem _ hcol hsum
    have hz := (Submodule.disjoint_def.mp hdis) _ hi ⟨p.val, rfl⟩
    exact p.property (hι (hz.trans ι.map_zero.symm))
  have hex (e : α) (he : e ∈ M.E) :
      ∃ x : BinaryVector, ∃ D : Finset α,
        (D : Set α) ⊆ B ∧ ρ e = ι x + ∑ b ∈ D, ρ b := by
    have heS : ρ e ∈ LinearMap.range ι ⊔ Submodule.span (ZMod 2) (ρ '' B) :=
      hspan.symm ▸ Submodule.subset_span ⟨e, he, rfl⟩
    obtain ⟨x, ⟨y, rfl⟩, z, hz, hxz⟩ := Submodule.mem_sup.mp heS
    obtain ⟨D, hD⟩ := exists_binary_subset_sum ρ B hz
    refine ⟨y, D.image Subtype.val, ?_, ?_⟩
    · intro b hb
      obtain ⟨d, _, rfl⟩ := Finset.mem_image.mp hb
      exact d.property
    · rw [Finset.sum_image (fun a _ b _ h => Subtype.ext h), hD]
      exact hxz.symm
  have hexall : ∀ e : α, ∃ x : BinaryVector, ∃ D : Finset α,
      (D : Set α) ⊆ B ∧ (e ∈ M.E → ρ e = ι x + ∑ b ∈ D, ρ b) ∧
      (e ∈ B → x = 0 ∧ D = {e}) ∧
      ∀ p, e = g p → x = p.val ∧ D = T p := by
    intro e
    by_cases heG : ∃ p, e = g p
    · obtain ⟨p, rfl⟩ := heG
      refine ⟨p.val, T p, hT p, fun _ => (hlift p).2,
        fun hh => (hgB p hh).elim, ?_⟩
      intro r hr
      have hpr : p = r := g.injective hr
      subst r; exact ⟨rfl, rfl⟩
    · by_cases heB : e ∈ B
      · refine ⟨0, {e}, ?_, ?_, fun _ => ⟨rfl, rfl⟩, ?_⟩
        · simpa using (Set.singleton_subset_iff.mpr heB)
        · intro _; simp
        · exact fun p hp => (heG ⟨p, hp⟩).elim
      · by_cases he : e ∈ M.E
        · obtain ⟨x, D, hDB, hcol⟩ := hex e he
          exact ⟨x, D, hDB, fun _ => hcol, fun hh => (heB hh).elim,
            fun p hp => (heG ⟨p, hp⟩).elim⟩
        · exact ⟨0, ∅, by simp, fun hh => (he hh).elim,
            fun hh => (heB hh).elim, fun p hp => (heG ⟨p, hp⟩).elim⟩
  choose t D hsupport hcol hb hg using hexall
  exact ⟨t, D, ⟨hBE, hB, hdis, hcol, hsupport, hb⟩, fun p => hg (g p) p rfl⟩

/-- The original Fano-minor and excluded-minor hypotheses give a complete
ground chart containing the entire actual contracted basis. Every one of
the seven preserved lift supports is precisely its normalized exception
class on that basis; extra quotient basis indices support none of them. -/
theorem Represents.exists_fano_contraction_ground_chart
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (C : Set α) (hC : M.Indep C)
    (f : FanoPoint ↪ α) (hf : (fano.mapEmbedding f).IsRestriction (M ／ C)) :
    letI : Fintype C := Fintype.ofFinite C
    ∃ (B : Set α) (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2))
      (t : α → BinaryVector) (D : α → Finset α) (g : FanoPoint ↪ α)
      (r : C → Option FanoPoint), C ⊆ B ∧ Function.Injective ι ∧
      LinearMap.range ι ⊔ Submodule.span (ZMod 2) (ρ '' B) =
        Submodule.span (ZMod 2) (ρ '' M.E) ∧
      FanoSupportChart M ρ ι t B D ∧
      ∀ p, g p ∈ M.E \ B ∧ t (g p) = p.val ∧
        ∀ b, b ∈ D (g p) ↔ ∃ hb : b ∈ C, r ⟨b, hb⟩ = some p := by
  classical
  let : Fintype C := Fintype.ofFinite C
  obtain ⟨ι, hι, hdis, g, r, hlift⟩ :=
    hρ.exists_fano_independent_contraction_normal_form hno C hC f hf
  let T : FanoPoint → Finset α :=
    fun p => (Finset.univ.filter (fun b : C => r b = some p)).image Subtype.val
  have hTC (p : FanoPoint) : (T p : Set α) ⊆ C := by
    intro b hb
    obtain ⟨d, _, rfl⟩ := Finset.mem_image.mp hb
    exact d.property
  have hTsum (p : FanoPoint) :
      (∑ b ∈ T p, ρ b) = ∑ b : C, (if r b = some p then (1 : ZMod 2) else 0) • ρ b.val := by
    rw [Finset.sum_image (fun a _ b _ h => Subtype.ext h)]
    simp only [Finset.sum_filter, ite_smul, one_smul, zero_smul]
  have hTlift (p : FanoPoint) : g p ∈ M.E ∧ ρ (g p) = ι p.val + ∑ b ∈ T p, ρ b :=
    ⟨(hlift p).1.1, by rw [hTsum]; exact (hlift p).2⟩
  let Tsub : FanoPoint → Finset C := fun p => Finset.univ.filter (fun b : C => r b = some p)
  have hsubLift (p : FanoPoint) : g p ∈ M.E ∧
      ρ (g p) = ι p.val + ∑ b ∈ Tsub p, ρ b.val := by
    refine ⟨(hlift p).1.1, ?_⟩
    rw [(hlift p).2]
    simp only [Tsub, Finset.sum_filter, ite_smul, one_smul, zero_smul]
  have hplane := fano_lift_plane_le_ground_span C hC.subset_ground ι g Tsub hsubLift
  obtain ⟨B, hBE, hCB, hBI, hBdis, hspan⟩ :=
    exists_column_span_complement_extension ρ M.E C (LinearMap.range ι)
      hC.subset_ground ((hρ _).mp hC).2 hdis hplane
  obtain ⟨t, D, hchart, hpoints⟩ := exists_fano_support_chart_preserving_lift B hBE hBI
    ι hι hBdis hspan g T (fun p => (hTC p).trans hCB) hTlift
  refine ⟨B, ι, t, D, g, r, hCB, hι, hspan, hchart, ?_⟩
  intro p
  refine ⟨⟨(hlift p).1.1, ?_⟩, (hpoints p).1, ?_⟩
  · intro hpB
    have ht0 := (hchart.basis (g p) hpB).1
    rw [(hpoints p).1] at ht0
    exact p.property ht0
  · intro b
    rw [(hpoints p).2]
    constructor
    · intro hb
      obtain ⟨d, hd, rfl⟩ := Finset.mem_image.mp hb
      exact ⟨d.property, (Finset.mem_filter.mp hd).2⟩
    · rintro ⟨hb, hr⟩
      exact Finset.mem_image.mpr ⟨⟨b, hb⟩, Finset.mem_filter.mpr ⟨Finset.mem_univ _, hr⟩, rfl⟩

end CycleDoubleCover.MatroidPaper
