import CycleDoubleCover.FanoSupportChains

/-! Whole support components have a single Fano attachment line. -/

namespace CycleDoubleCover.MatroidPaper

open Set Module
open scoped Matroid

variable {α : Type*} [Finite α] {M : Matroid α} {n : ℕ}
  {ρ : α → Fin n → ZMod 2}

omit [Finite α] in
private theorem FanoSupportChain.snoc
    {t : α → BinaryVector} {D : α → Finset α} {a b c : α} {k : ℕ}
    (p : FanoSupportChain M t D a b k)
    (z : α) (hz : z ∈ M.E) (htz : t z = 0) (hb : b ∈ D z) (hc : c ∈ D z) :
    FanoSupportChain M t D a c (k + 1) := by
  induction p with
  | nil a => exact .cons z hz htz hb hc (.nil c)
  | cons w hw htw ha hu p ih => exact .cons w hw htw ha hu (ih hb)

/-- A support chain may traverse any original ground column. -/
inductive FanoGroundSupportChain (M : Matroid α) (D : α → Finset α) : α → α → ℕ → Prop
  | nil (a : α) : FanoGroundSupportChain M D a a 0
  | cons {a b d : α} {k : ℕ} (z : α) (hz : z ∈ M.E)
      (ha : a ∈ D z) (hb : b ∈ D z) (p : FanoGroundSupportChain M D b d k) :
      FanoGroundSupportChain M D a d (k + 1)

omit [Finite α] in
theorem FanoGroundSupportChain.append
    {D : α → Finset α} {a b c : α} {k l : ℕ}
    (p : FanoGroundSupportChain M D a b k) (q : FanoGroundSupportChain M D b c l) :
    FanoGroundSupportChain M D a c (k + l) := by
  induction p with
  | nil a => simpa only [Nat.zero_add] using q
  | @cons a u b k z hz ha hu p ih =>
    have h := FanoGroundSupportChain.cons z hz ha hu (ih q)
    convert h using 1; omega

omit [Finite α] in
theorem FanoGroundSupportChain.reverse
    {D : α → Finset α} {a b : α} {k : ℕ} (p : FanoGroundSupportChain M D a b k) :
    FanoGroundSupportChain M D b a k := by
  induction p with
  | nil a => exact .nil a
  | cons z hz ha hu p ih => exact ih.append (.cons z hz hu ha (.nil _))

private theorem ground_chain_alignment_aux
    {ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)} {t C D}
    (h : FanoSupportChart M ρ ι t C D)
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    {b d : α} {l : ℕ} (p : FanoGroundSupportChain M D b d l) :
    ∀ (e f a : α) (k : ℕ), e ∈ M.E → f ∈ M.E → t e ≠ 0 → t f ≠ 0 →
      a ∈ D e → d ∈ D f → FanoSupportChain M t D a b k → t e = t f := by
  induction p with
  | nil b =>
    intro e f a k he hf hte htf hae hbf q
    exact FanoSupportChart.chain_trace_alignment hρ hno hι hFano k C D h
      e f a b he hf hte htf hae hbf q
  | @cons b u d l z hz hb hu p ih =>
    intro e f a k he hf hte htf hae hdf q
    by_cases htz : t z = 0
    · exact ih e f a (k + 1) he hf hte htf hae hdf (q.snoc z hz htz hb hu)
    · have hez := FanoSupportChart.chain_trace_alignment hρ hno hι hFano k C D h
        e z a b he hz hte htz hae hb q
      exact hez.trans (ih z f u 0 hz hf htz htf hu hdf (.nil u))

/-- All original support edges, including nonzero-trace edges, propagate
the attachment line throughout a component. -/
theorem FanoSupportChart.ground_chain_trace_alignment
    {ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)} {t C D}
    (h : FanoSupportChart M ρ ι t C D)
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    {e f a b : α} {k : ℕ} (he : e ∈ M.E) (hf : f ∈ M.E)
    (hte : t e ≠ 0) (htf : t f ≠ 0) (hae : a ∈ D e) (hbf : b ∈ D f)
    (p : FanoGroundSupportChain M D a b k) : t e = t f :=
  ground_chain_alignment_aux h hρ hno hι hFano p e f a 0 he hf hte htf hae hbf (.nil a)

/-- Connectivity generated by the supports of actual ground columns. -/
def FanoSupportConnected (M : Matroid α) (D : α → Finset α) (a b : α) : Prop :=
  ∃ k, FanoGroundSupportChain M D a b k

omit [Finite α] in
theorem FanoSupportConnected.refl (D : α → Finset α) (a : α) : FanoSupportConnected M D a a :=
  ⟨0, .nil a⟩

omit [Finite α] in
theorem FanoSupportConnected.symm {D : α → Finset α} {a b : α}
    (h : FanoSupportConnected M D a b) : FanoSupportConnected M D b a := by
  obtain ⟨k, p⟩ := h
  exact ⟨k, p.reverse⟩

omit [Finite α] in
theorem FanoSupportConnected.trans {D : α → Finset α} {a b c : α}
    (h : FanoSupportConnected M D a b) (h' : FanoSupportConnected M D b c) :
    FanoSupportConnected M D a c := by
  obtain ⟨k, p⟩ := h
  obtain ⟨l, q⟩ := h'
  exact ⟨k + l, p.append q⟩

omit [Finite α] in
theorem FanoSupportConnected.of_common_support {D : α → Finset α} {a b z : α}
    (hz : z ∈ M.E) (ha : a ∈ D z) (hb : b ∈ D z) : FanoSupportConnected M D a b :=
  ⟨1, .cons z hz ha hb (.nil b)⟩

/-- The part of the original ground attached to a quotient support component. -/
def fanoSupportGround (M : Matroid α) (D : α → Finset α) (c : α) : Set α :=
  {e ∈ M.E | ∃ b ∈ D e, FanoSupportConnected M D c b}

/-- A whole original-ground attachment component uses at most one Fano line.
The component and its trace are selected from actual coordinate data. -/
theorem FanoSupportChart.component_trace_line
    {ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)} {t C D}
    (h : FanoSupportChart M ρ ι t C D)
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val) (c : α) :
    ∃ p : BinaryVector,
      (∀ e ∈ fanoSupportGround M D c, t e = 0 ∨ t e = p) ∧
      (p = 0 ∨ ∃ e ∈ fanoSupportGround M D c, t e = p ∧ p ≠ 0) := by
  classical
  by_cases hex : ∃ e ∈ fanoSupportGround M D c, t e ≠ 0
  · obtain ⟨e, he, hte⟩ := hex
    refine ⟨t e, ?_, Or.inr ⟨e, he, rfl, hte⟩⟩
    intro f hf
    by_cases htf : t f = 0
    · exact Or.inl htf
    · apply Or.inr
      obtain ⟨a, hae, hca⟩ := he.2
      obtain ⟨b, hbf, hcb⟩ := hf.2
      obtain ⟨k, q⟩ := hcb.symm.trans hca
      exact h.ground_chain_trace_alignment hρ hno hι hFano hf.1 he.1 htf hte hbf hae q
  · refine ⟨0, ?_, Or.inl rfl⟩
    intro e he
    exact Or.inl (by by_contra hte; exact hex ⟨e, he, hte⟩)

end CycleDoubleCover.MatroidPaper
