import CycleDoubleCover.FanoContractionAttachments

/-!
# Small-span obstruction for attachments to a Fano restriction

The excluded minor forces every attachment in three occupied affine
directions into a space generated by two outside columns and one Fano-plane
direction. The resulting rank bound gives a genuine matroid separation.
-/

namespace CycleDoubleCover.MatroidPaper

open Set Module Matrix
open scoped Matroid

variable {α : Type*} [Finite α] {M : Matroid α} {n : ℕ}
  {ρ : α → Fin n → ZMod 2}

private theorem binary_add_self {r : ℕ} (x : Fin r → ZMod 2) : x + x = 0 := by
  funext i
  exact CharTwo.add_self_eq_zero _

/-- A nontrivial pair exhausts its outside affine Fano coset under the
actual dual-Fano minor exclusion. -/
theorem Represents.fano_pair_exhausts_affine_coset
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (a a' e : α) (ha : a ∈ M.E) (ha' : a' ∈ M.E) (he : e ∈ M.E)
    (hout : ρ a ∉ Set.range ι) (p d : BinaryVector) (hp : p ≠ 0)
    (hpair : ρ a' = ρ a + ι p) (hecol : ρ e = ρ a + ι d) : d = 0 ∨ d = p := by
  classical
  by_cases hd0 : d = 0
  · exact Or.inl hd0
  by_cases hdp : d = p
  · exact Or.inr hdp
  apply False.elim
  let b : Fin 3 → α := ![a, a', e]
  let t : Fin 3 → BinaryVector := ![0, p, d]
  have ht : Function.Injective t := by
    intro i j hij
    fin_cases i <;> fin_cases j <;> simp_all [t]
  have hbground : ∀ i, b i ∈ M.E := by
    intro i; fin_cases i <;> simp [b, ha, ha', he]
  have hbcol : ∀ i, ρ (b i) = ρ a + ι (t i) := by
    intro i; fin_cases i <;> simp [b, t, hpair, hecol]
  exact hno (hρ.has_dualFano_minor_of_fano_affine_triple
    ι hι hFano (ρ a) hout b hbground t ht hbcol)

/-- If all outside attachments use three occupied affine directions and
one direction contains a nontrivial pair, minor exclusion forces all of
them into the span of two outside columns and the pair's one direction. -/
theorem Represents.outside_fano_span_le_three_generators
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (a a' b c : α) (ha : a ∈ M.E) (ha' : a' ∈ M.E)
    (hb : b ∈ M.E) (hc : c ∈ M.E)
    (hao : ρ a ∉ Set.range ι) (hbo : ρ b ∉ Set.range ι) (hco : ρ c ∉ Set.range ι)
    (hab : ρ a + ρ b ∉ Set.range ι) (hac : ρ a + ρ c ∉ Set.range ι)
    (p d : BinaryVector) (hp : p ≠ 0)
    (hpair : ρ a' = ρ a + ι p) (hconnect : ρ b = ρ a + ρ c + ι d)
    (hdirections : ∀ e ∈ M.E, ρ e ∉ Set.range ι →
      (∃ t, ρ e = ρ a + ι t) ∨ (∃ t, ρ e = ρ b + ι t) ∨ (∃ t, ρ e = ρ c + ι t)) :
    Submodule.span (ZMod 2) (ρ '' {e ∈ M.E | ρ e ∉ Set.range ι}) ≤
      Submodule.span (ZMod 2) ({ρ a, ρ b, ι p} : Set (Fin n → ZMod 2)) := by
  classical
  let K := Submodule.span (ZMod 2) ({ρ a, ρ b, ι p} : Set (Fin n → ZMod 2))
  have hKa : ρ a ∈ K := Submodule.subset_span (by simp)
  have hKb : ρ b ∈ K := Submodule.subset_span (by simp)
  have hKp : ι p ∈ K := Submodule.subset_span (by simp)
  have hoffset (r e : α) (hr : r ∈ M.E) (hro : ρ r ∉ Set.range ι)
      (har : ρ a + ρ r ∉ Set.range ι) (he : e ∈ M.E) (t : BinaryVector)
      (hcol : ρ e = ρ a + ρ r + ι t) : t = 0 ∨ t = p := by
    let f : Fin 3 → α := ![a, a', e]
    have hf : ∀ i, f i ∈ M.E := by
      intro i; fin_cases i <;> simp [f, ha, ha', he]
    exact hρ.fano_pair_offset_after_contraction hno ι hι hFano r hr hro f hf hao har
      p t hp (by simpa [f] using hpair) (by simpa [f] using hcol)
  have hd : d = 0 ∨ d = p := hoffset c b hc hco hac hb d hconnect
  have hKd : ι d ∈ K := by
    rcases hd with rfl | rfl
    · rw [map_zero]; exact K.zero_mem
    · exact hKp
  have hceq : ρ c = ρ a + ρ b + ι d := by
    rw [hconnect]
    have hh : ρ a + (ρ a + ρ c + ι d) + ι d =
        ρ c + (ρ a + ρ a) + (ι d + ι d) := by abel
    rw [hh, binary_add_self, binary_add_self, add_zero, add_zero]
  have hKc : ρ c ∈ K := hceq ▸ K.add_mem (K.add_mem hKa hKb) hKd
  have hKt {t : BinaryVector} (ht : t = 0 ∨ t = p) : ι t ∈ K := by
    rcases ht with rfl | rfl
    · rw [map_zero]; exact K.zero_mem
    · exact hKp
  apply Submodule.span_le.mpr
  rintro _ ⟨e, ⟨he, heo⟩, rfl⟩
  rcases hdirections e he heo with ⟨t, ht⟩ | ⟨t, ht⟩ | ⟨t, ht⟩
  · have hline := hρ.fano_pair_exhausts_affine_coset hno ι hι hFano
      a a' e ha ha' he hao p t hp hpair ht
    exact ht ▸ K.add_mem hKa (hKt hline)
  · have hcol : ρ e = ρ a + ρ c + ι (d + t) := by
      rw [ht, hconnect, map_add]
      abel
    have hline := hoffset c e hc hco hac he (d + t) hcol
    exact hcol ▸ K.add_mem (K.add_mem hKa hKc) (hKt hline)
  · have hcol : ρ e = ρ a + ρ b + ι (d + t) := by
      rw [ht, hceq, map_add]
      abel
    have hline := hoffset b e hb hbo hab he (d + t) hcol
    exact hcol ▸ K.add_mem (K.add_mem hKa hKb) (hKt hline)

/-- The actual ground represented in the Fano plane. -/
def fanoPlaneGround (M : Matroid α) (ρ : α → Fin n → ZMod 2)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) : Set α :=
  {e ∈ M.E | ρ e ∈ Set.range ι}

/-- The actual ground represented outside the Fano plane. -/
def fanoOutsideGround (M : Matroid α) (ρ : α → Fin n → ZMod 2)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) : Set α :=
  {e ∈ M.E | ρ e ∉ Set.range ι}

/-- The excluded-minor alignment bounds the actual rank of the complete
outside ground, without an independence or decomposition premise. -/
theorem Represents.outside_fano_rank_le_three_of_affine_directions
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (a a' b c : α) (ha : a ∈ M.E) (ha' : a' ∈ M.E)
    (hb : b ∈ M.E) (hc : c ∈ M.E)
    (hao : ρ a ∉ Set.range ι) (hbo : ρ b ∉ Set.range ι) (hco : ρ c ∉ Set.range ι)
    (hab : ρ a + ρ b ∉ Set.range ι) (hac : ρ a + ρ c ∉ Set.range ι)
    (p d : BinaryVector) (hp : p ≠ 0)
    (hpair : ρ a' = ρ a + ι p) (hconnect : ρ b = ρ a + ρ c + ι d)
    (hdirections : ∀ e ∈ M.E, ρ e ∉ Set.range ι →
      (∃ t, ρ e = ρ a + ι t) ∨ (∃ t, ρ e = ρ b + ι t) ∨ (∃ t, ρ e = ρ c + ι t)) :
    MatroidUnion.rank M (fanoOutsideGround M ρ ι) ≤ 3 := by
  classical
  have hspan := hρ.outside_fano_span_le_three_generators hno ι hι hFano a a' b c
    ha ha' hb hc hao hbo hco hab hac p d hp hpair hconnect hdirections
  have hcard : ({ρ a, ρ b, ι p} : Finset (Fin n → ZMod 2)).card ≤ 3 := Finset.card_le_three
  have hfinrank : finrank (ZMod 2)
      (Submodule.span (ZMod 2) ({ρ a, ρ b, ι p} : Set (Fin n → ZMod 2))) ≤ 3 := by
    have hcoeq : (({ρ a, ρ b, ι p} : Finset (Fin n → ZMod 2)) : Set (Fin n → ZMod 2)) =
        {ρ a, ρ b, ι p} := by ext x; simp
    have hfr := (finrank_span_finset_le_card (R := ZMod 2)
      ({ρ a, ρ b, ι p} : Finset (Fin n → ZMod 2))).trans hcard
    change finrank (ZMod 2) (Submodule.span (ZMod 2)
      (({ρ a, ρ b, ι p} : Finset (Fin n → ZMod 2)) : Set (Fin n → ZMod 2))) ≤ 3 at hfr
    rw [hcoeq] at hfr
    exact hfr
  rw [hρ.rank_eq_finrank_span (fun _ h => h.1)]
  exact (Submodule.finrank_mono hspan).trans hfinrank

/-- A Fano-plane side and an outside side of rank at most three give an
actual one- or two-separation whenever the total matroid rank is at least five. -/
theorem Represents.exists_small_separation_of_fano_outside_rank_le_three
    (hρ : Represents M (ZMod 2) ρ)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (hrank : 5 ≤ MatroidUnion.rank M M.E)
    (houtside : MatroidUnion.rank M (fanoOutsideGround M ρ ι) ≤ 3) :
    IsOneSeparation M (fanoPlaneGround M ρ ι) (fanoOutsideGround M ρ ι) ∨
    IsTwoSeparation M (fanoPlaneGround M ρ ι) (fanoOutsideGround M ρ ι) := by
  classical
  let A := fanoPlaneGround M ρ ι
  let B := fanoOutsideGround M ρ ι
  change MatroidUnion.rank M B ≤ 3 at houtside
  have hAB : Disjoint A B := by
    apply Set.disjoint_left.mpr
    exact fun _ ha hb => hb.2 ha.2
  have hground : A ∪ B = M.E := by
    ext e
    simp only [A, B, fanoPlaneGround, fanoOutsideGround, Set.mem_union, Set.mem_ofPred_eq]
    tauto
  have hAsub : A ⊆ M.E := fun _ h => h.1
  have hrange : finrank (ZMod 2) (LinearMap.range ι) = 3 := by
    rw [LinearMap.finrank_range_of_inj hι]
    simp
  have hAsp : Submodule.span (ZMod 2) (ρ '' A) ≤ LinearMap.range ι := by
    apply Submodule.span_le.mpr
    rintro _ ⟨e, he, rfl⟩
    exact he.2
  have hArank : MatroidUnion.rank M A ≤ 3 := by
    rw [hρ.rank_eq_finrank_span hAsub, ← hrange]
    exact Submodule.finrank_mono hAsp
  obtain ⟨ea, hea, hcola⟩ := hFano (triangleFanoPoints 0)
  obtain ⟨eb, heb, hcolb⟩ := hFano (triangleFanoPoints 1)
  have hab : ea ≠ eb := by
    intro hab
    have hcol : (triangleFanoPoints 0).val = (triangleFanoPoints 1).val :=
      hι (hcola.symm.trans (hab ▸ hcolb))
    have hne : (triangleFanoPoints 0).val ≠ (triangleFanoPoints 1).val := by decide +kernel
    exact hne hcol
  have haA : ea ∈ A := ⟨hea, ⟨_, hcola.symm⟩⟩
  have hbA : eb ∈ A := ⟨heb, ⟨_, hcolb.symm⟩⟩
  have hAcard : 2 ≤ A.ncard := by
    calc
      2 = ({ea, eb} : Set α).ncard := (Set.ncard_pair hab).symm
      _ ≤ A.ncard := Set.ncard_le_ncard (Set.pair_subset haA hbA)
  have hBrank := MatroidUnion.rank_le_ncard M B
  have hdim := hρ.partition_intersection_finrank hground
  have hBcard : 2 ≤ B.ncard := by omega
  by_cases hzero : MatroidUnion.rank M A + MatroidUnion.rank M B = MatroidUnion.rank M M.E
  · exact Or.inl ⟨hAB, hground, (by omega : 1 ≤ A.ncard), (by omega : 1 ≤ B.ncard), hzero⟩
  · have hone : MatroidUnion.rank M A + MatroidUnion.rank M B =
        MatroidUnion.rank M M.E + 1 := by omega
    exact Or.inr ⟨hAB, hground, hAcard, hBcard, hone⟩

/-- The complete exclusion-sensitive structural conclusion: three affine
attachment directions and a nontrivial pair force a genuine one- or
two-separation in every represented matroid of rank at least five. -/
theorem Represents.exists_small_separation_of_fano_three_affine_directions
    (hρ : Represents M (ZMod 2) ρ) (hno : HasNoDualFanoMinor M)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (a a' b c : α) (ha : a ∈ M.E) (ha' : a' ∈ M.E)
    (hb : b ∈ M.E) (hc : c ∈ M.E)
    (hao : ρ a ∉ Set.range ι) (hbo : ρ b ∉ Set.range ι) (hco : ρ c ∉ Set.range ι)
    (hab : ρ a + ρ b ∉ Set.range ι) (hac : ρ a + ρ c ∉ Set.range ι)
    (p d : BinaryVector) (hp : p ≠ 0)
    (hpair : ρ a' = ρ a + ι p) (hconnect : ρ b = ρ a + ρ c + ι d)
    (hdirections : ∀ e ∈ M.E, ρ e ∉ Set.range ι →
      (∃ t, ρ e = ρ a + ι t) ∨ (∃ t, ρ e = ρ b + ι t) ∨ (∃ t, ρ e = ρ c + ι t))
    (hrank : 5 ≤ MatroidUnion.rank M M.E) :
    IsOneSeparation M (fanoPlaneGround M ρ ι) (fanoOutsideGround M ρ ι) ∨
    IsTwoSeparation M (fanoPlaneGround M ρ ι) (fanoOutsideGround M ρ ι) := by
  apply hρ.exists_small_separation_of_fano_outside_rank_le_three ι hι hFano hrank
  exact hρ.outside_fano_rank_le_three_of_affine_directions hno ι hι hFano a a' b c
    ha ha' hb hc hao hbo hco hab hac p d hp hpair hconnect hdirections

/-- Irreducibility and a full Fano restriction force the outside side to
have rank at least four once the total rank is at least five. -/
theorem Represents.fano_outside_rank_ge_four_of_irreducible
    (hρ : Represents M (ZMod 2) ρ)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (hrank : 5 ≤ MatroidUnion.rank M M.E)
    (hsep : ∀ A B : Set α, ¬ IsOneSeparation M A B ∧ ¬ IsTwoSeparation M A B) :
    4 ≤ MatroidUnion.rank M (fanoOutsideGround M ρ ι) := by
  by_contra h
  rcases hρ.exists_small_separation_of_fano_outside_rank_le_three ι hι hFano hrank
    (by omega) with h₁ | h₂
  · exact (hsep _ _).1 h₁
  · exact (hsep _ _).2 h₂

/-- In a two-dimensional quotient by a full Fano plane, the forced outside
ground size gives an actual nontrivial pair in one affine direction. This
derives the pair from rank and irreducibility, with no attachment premise. -/
theorem Represents.exists_fano_affine_pair_of_two_dimensional_quotient
    (hρ : Represents M (ZMod 2) ρ)
    (ι : BinaryVector →ₗ[ZMod 2] (Fin n → ZMod 2)) (hι : Function.Injective ι)
    (hFano : ∀ p : FanoPoint, ∃ e ∈ M.E, ρ e = ι p.val)
    (hrank : 5 ≤ MatroidUnion.rank M M.E)
    (hsep : ∀ A B : Set α, ¬ IsOneSeparation M A B ∧ ¬ IsTwoSeparation M A B)
    (π : (Fin n → ZMod 2) →ₗ[ZMod 2] (Fin 2 → ZMod 2))
    (hker : LinearMap.ker π = LinearMap.range ι) :
    ∃ a ∈ M.E, ∃ a' ∈ M.E, ∃ p : BinaryVector,
      ρ a ∉ Set.range ι ∧ p ≠ 0 ∧ ρ a' = ρ a + ι p := by
  classical
  let : Fintype α := Fintype.ofFinite α
  let B := fanoOutsideGround M ρ ι
  have hBrank := hρ.fano_outside_rank_ge_four_of_irreducible ι hι hFano hrank hsep
  have hBcard : 4 ≤ B.ncard := hBrank.trans (MatroidUnion.rank_le_ncard M B)
  have hsize : 4 ≤ M.E.ncard := by
    have h := MatroidUnion.rank_le_ncard M M.E
    omega
  have hρinj := hρ.injOn_of_no_one_or_two_separation hsize hsep
  have hpairs : ∃ a ∈ B, ∃ a' ∈ B, a ≠ a' ∧ π (ρ a) = π (ρ a') := by
    by_contra hn
    have hinj : Set.InjOn (fun a => π (ρ a)) B := by
      intro a ha a' ha' heq
      by_contra hne
      exact hn ⟨a, ha, a', ha', hne, heq⟩
    let S := B.toFinset
    let P := S.image (fun a => π (ρ a))
    have hSB : (S : Set α) = B := Set.coe_toFinset B
    have hcard : P.card = B.ncard := by
      rw [Finset.card_image_of_injOn (fun a ha a' ha' h => hinj
        (hSB ▸ ha) (hSB ▸ ha') h)]
      simp only [S, Set.toFinset_card, Set.fintypeCard_eq_ncard]
    have hzero : (0 : Fin 2 → ZMod 2) ∉ P := by
      intro hz
      obtain ⟨a, ha, ha0⟩ := Finset.mem_image.mp hz
      have haB : a ∈ B := by simpa only [S, Set.mem_toFinset] using ha
      have hmem : ρ a ∈ LinearMap.ker π := ha0
      rw [hker] at hmem
      exact haB.2 hmem
    have hsub : P ⊆ Finset.univ.erase 0 := by
      intro x hx
      simp only [Finset.mem_erase, Finset.mem_univ, and_true]
      exact fun hx0 => hzero (hx0 ▸ hx)
    have hle := Finset.card_le_card hsub
    have htotal : (Finset.univ.erase (0 : Fin 2 → ZMod 2)).card = 3 := by decide +kernel
    rw [hcard, htotal] at hle
    omega
  obtain ⟨a, ha, a', ha', hne, heq⟩ := hpairs
  have hdiff : ρ a' - ρ a ∈ LinearMap.ker π := by
    rw [LinearMap.mem_ker, map_sub, heq, sub_self]
  rw [hker] at hdiff
  obtain ⟨p, hp⟩ := hdiff
  have hcol : ρ a' = ρ a + ι p := by
    have hh := eq_sub_iff_add_eq.mp hp
    exact hh.symm.trans (add_comm _ _)
  have hp0 : p ≠ 0 := by
    intro hp0
    have hcol' : ρ a' = ρ a := by simpa only [hp0, map_zero, add_zero] using hcol
    exact hne (hρinj ha.1 ha'.1 hcol'.symm)
  exact ⟨a, ha.1, a', ha'.1, p, ha.2, hp0, hcol⟩

end CycleDoubleCover.MatroidPaper
